# docker-compose.dev.yml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: acquisitions-app-dev
    ports:
      - "3001:3000"   # свободный порт для dev
    env_file:
      - .env.development
    volumes:
      - ./:/app
      - /app/node_modules
      - ./db/dev.db:/app/db/dev.db
    command: npm run dev